name: Azure Static Web Apps CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ['main']

permissions:
  contents: read
  pull-requests: write

env:
  DOTNET_VERSION: '8.x'
  APP_PROJECT_FILE: 'src/WebApp/WebApp.csproj'
  APP_OUTPUT_LOCATION: 'src/bin/Release/net8.0/publish'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    environment: ${{ github.event_name == 'push' && 'Production' || 'Staging' }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: 'nuget'
      - name: Restore dependencies
        run: dotnet restore
      - name: Verify formatting
        run: dotnet format --verify-no-changes --no-restore
      - name: Build solution
        run: dotnet build -c Release --no-restore
      - name: Run tests
        run: dotnet test -c Release --no-restore
      - name: Publish web app
        run: dotnet publish ${{ env.APP_PROJECT_FILE }} -c Release --no-restore --no-build
